config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#welcome'

  get 'teste', to: 'teste#teste'

  resources :articles
  # resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
    belongs_to :user

    validates :title, presence: true, length: {minimum:6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_currenty_route

    protected

    def set_currenty_route
        params[:currenty_route] = "#{params[:controller]}/#{params[:action]}"
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    

    def index
        @articles = Article.all
    end

    def show
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if( @article.save )
            flash[:notice] = "Article was created successfully!"
            redirect_to @article
        else 
            render 'new'
        end
    end

    def edit
    end

    def update
        if( @article.update(article_params) )
            flash[:notice] = "Article was updated successfully!"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy()
        flash[:notice] = "Article was deleted successfully!"
        redirect_to '/articles'
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def welcome
        render "pages/welcome"
    end

end

app/controllers/teste_controller.rb
class TesteController < ApplicationController
    def teste
        render html: "OPa"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teste_helper.rb
module TesteHelper
end

app/views/articles/_article.html.erb
<article class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span class="font-weight-bold">
            <%= article.title.to_s + ' - ' + article.id.to_s %>
        </span>
        <div>
            <a class="btn btn-outline-success" href="<%= request.base_url + '/articles/' + article.id.to_s %>">Show</a>
            <a class="btn btn-outline-info" href="<%= request.base_url + '/articles/' + article.id.to_s + '/edit' %>">Edit</a>
            <%= link_to 'Delete', article_path(article), method: :delete, data:{confirm:"Are you sure?"}, class: "btn btn-outline-danger" %>
        </div>
    </div>
    <div class="card-body">
        <%= article.description %>
    </div>
</article>

app/views/articles/_form.html.erb
<style>
    .textarea-description {
        min-height: 250px;
        resize: none;
    }
</style>

<% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |error| %>
        <h5 class="error"><%= error %></h5>
    <% end %>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title, class: "font-weight-bold" %><br/> 
        <%= f.text_field :title, class:"form-control input-title" %>
    </p>
    <p>
        <div class="d-flex justify-content-between">
            <%= f.label :description, class: "font-weight-bold" %><br/>
            <div>
                <span id="span-current-length">
                    <%= (@article[:description].present?) ? @article[:description].length : 0 %>
                </span>
                <span>/</span>
                <span id="span-max-length">300</span>
            </div>
        </div>
        <%= f.text_area :description, class:"form-control textarea-description" %> 
    </p>
    <p>
        <%= f.submit (@article.id) ? 'Save changes' : 'Create article', class: 'btn btn-success' %>
        <% if @article[:id].present? %>
            <%= link_to 'Delete', article_path(@article), method: :delete, data:{confirm:"Are you sure?"}, class: "btn btn-outline-danger" %>
        <% end %>
    </p>
<% end %>

<script>
    spanCurrentLength = document.querySelector('#span-current-length');
    textareaDescription = document.querySelector('.textarea-description');

    function verifyDescriptionMinimumLength(){
        length = textareaDescription.value.length;
        if( length < 10 ){
            spanCurrentLength.classList.add('text-danger');
            return;
        }
        spanCurrentLength.classList.remove('text-danger');
    }

    function renderSpanCurrentLength(length){
        spanCurrentLength.innerHTML = length;
        verifyDescriptionMinimumLength();
    }
    
    textareaDescription.addEventListener('keyup', function(e){
        renderSpanCurrentLength(this.value.length);
    });

    verifyDescriptionMinimumLength();
</script>

app/views/articles/edit.html.erb
<main class="main">
    <h3 class="page-title">Editing article</h3>

    <%= render 'form' %>
</main>

app/views/articles/index.html.erb
<style>
    article.card {
        margin-top: 20px;
        transition: box-shadow 0.3s;
        color: #333;
    }

    article:hover {
        box-shadow: 2px 2px 5px rgba(0,0,0,0.2)
    }

    article .btn {
        font-weight: bold;
    }
</style>

<main class="main">
    <div class="d-flex justify-content-between">
        <h3 class="font-weight-bold">Articles list</h3>
        <%= link_to "Create new article", new_article_path, class:"btn btn-outline-dark" %>
    </div>

    <%= render partial: "article", collection: @articles, as: :article %>
</main>

app/views/articles/new.html.erb
<main class="main">
  <h3 class="page-title">Create a new article</h3>

  <%= render 'form' %>
</main>

app/views/articles/show.html.erb
<style>
    section.article {
        display: flex;
        justify-content: center;
    }
    div.card {
        max-width: 1024px;
    }
</style>

<main class="main">

    <section class="article">
        <div class="card w-100">
            <div class="card-body">
                <h2><%= @article.title %></h2>
                <hr/>
                <p><strong><%= @article.description %></strong></p>
            </div>
        </div>
    </section>

</main>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Rails blog</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <h5 class="notice"><%= msg %></h5>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="" href="#">
        <img id="navbar-logo" src="<%= request.base_url %>/blog-logo-black.png" />
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item pl-4 <%= 'active' if params[:currenty_route] == 'pages/welcome' %>">
            <a class="nav-link" href="<%= request.base_url %>/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item <%= 'active' if params[:currenty_route] == 'articles/index' %>">
            <a class="nav-link" href="<%= request.base_url %>/articles">Articles</a>
        </li>
        <li class="nav-item <%= 'active' if params[:currenty_route] == 'articles/new' %>">
            <a class="nav-link" href="<%= request.base_url %>/articles/new">New article</a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
        </li>
        <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button id="btnSearch" class="btn btn-outline-dark btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div id="page-content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/welcome.html.erb
<style>
    .onTop {
        background-color: transparent;
        box-shadow: none;
        color: white !important;
        border-bottom: 1px solid rgba(255,255,255,0.1);
    }

    .onTop .nav-link{
        color: #eee !important;
    }

    .onTop .nav-link:hover{
        color: #ED1C24 !important;
    }

    h1{
        color: white;
        text-shadow: 3px 3px 5px rgba(0,0,0,0.5);
    }
    p{
        color: white;
        text-shadow: 3px 3px 3px rgba(0,0,0,0.5);
    }
    .onTop .active a.nav-link{
        color: #ED1C24 !important;
    }
</style>
<div class="bg-image">
    <div class="div-glass">
        <h1 class="display-4">Welcome to <span class="text-danger">Rails</span> Blog!</h1>
        <p class="lead">Here you will find worthy read content about ruby on rails world.</p>
        <p>Feel free to contribute to out community with your knowledge and experience.</p>
        <a class="btn btn-danger btn-lg" href="#" role="button">Sign up</a>
    </div>
</div>

<div class="bg-info">
        Opa
</div>

<script>
    base_url = '<%= request.base_url %>'
</script>
<script defer src="<%= request.base_url %>/js/pages/welcome.js"></script>